---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    groups:
      github-actions:
        patterns:
          - "*"
